SET SCHEMA 'sptransp';

DELETE FROM ST_DESTINATION;
DELETE FROM ST_GOODS;
DELETE FROM ST_DEPARTMENT;

-- Destinations
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (1, 'Earth', 'EARTH', 'Solar system planet');
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (2, 'Moon', 'MOON', 'Earth''s satellite');
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (3, 'Mars', 'MARS', 'Solar system planet');
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (4, 'Phobos', 'MARS_PHOBOS', 'Mar''s satellite');
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (5, 'Deimos', 'MARS_DEIMOS', 'Mar''s satellite');
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (6, 'Io', 'JUPITER_IO', 'Jupiter''s satellite');
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (7, 'Europa', 'JUPITER_EUROPA', 'Jupiter''s satellite');
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (8, 'Ganymede', 'JUPITER_GANYMEDE', 'Jupiter''s satellite');
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (9, 'Callisto', 'JUPITER_CALLISTO', 'Jupiter''s satellite');
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (10, 'Titan', 'SATURN_TITAN', 'Saturn''s satellite');
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (11, 'Rhea', 'SATURN_RHEA', 'Saturn''s satellite');
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (12, 'Dione', 'SATURN_DIONE', 'Saturn''s satellite');
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (13, 'Tethys', 'SATURN_TETHYS', 'Saturn''s satellite');
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (14, 'Mimas', 'SATURN_MIMAS', 'Saturn''s satellite');
INSERT INTO ST_DESTINATION(ID, NAME, CODE, DESTINATION_COMMENT) VALUES (15, 'Enceladus', 'SATURN_ENCELADUS', 'Saturn''s satellite');

-- Goods
INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (1, 'Oil', 'OIL');
INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (2, 'Food', 'FOOD');
INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (3, 'Machine tool', 'MACHINE_TOOL');
INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (4, 'Medicine', 'MEDICINE');
INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (5, 'Weapon', 'WEAPON');

-- Departments
INSERT INTO ST_DEPARTMENT(ID, NAME, CODE) VALUES (1, 'Law compliance', 'LAW_COMPLIANCE');
INSERT INTO ST_DEPARTMENT(ID, NAME, CODE) VALUES (2, 'Shuttle compliance', 'SHUTTLE_COMPLIANCE');
INSERT INTO ST_DEPARTMENT(ID, NAME, CODE) VALUES (3, 'Goods inspection', 'GOODS_INSPECTION');
INSERT INTO ST_DEPARTMENT(ID, NAME, CODE) VALUES (4, 'Journey supervision', 'JOURNEY_SUPERVISION');
INSERT INTO ST_DEPARTMENT(ID, NAME, CODE) VALUES (5, 'Human resources', 'HR');
