SET SCHEMA 'sptransp';

DELETE FROM ST_DESTINATION;
DELETE FROM ST_GOODS;
DELETE FROM ST_DEPARTMENT;

-- Destinations
INSERT INTO ST_DESTINATION(ID, NAME, CODE) VALUES (1, 'Earth', 'EARTH');
INSERT INTO ST_DESTINATION(ID, NAME, CODE) VALUES (2, 'Moon', 'MOON');
INSERT INTO ST_DESTINATION(ID, NAME, CODE) VALUES (3, 'Mars', 'MARS');
INSERT INTO ST_DESTINATION(ID, NAME, CODE) VALUES (4, 'Titan', 'TITAN');

-- Goods
INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (1, 'Oil', 'OIL');
INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (2, 'Food', 'FOOD');
INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (3, 'Machine tool', 'MACHINE_TOOL');
INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (4, 'Medicine', 'MEDICINE');
INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (5, 'Weapon', 'WEAPON');

-- Departments
INSERT INTO ST_DEPARTMENT(ID, NAME, CODE) VALUES (1, 'Law compliance', 'LAW_COMPLIANCE');
INSERT INTO ST_DEPARTMENT(ID, NAME, CODE) VALUES (2, 'Shuttle compliance', 'SHUTTLE_COMPLIANCE');
INSERT INTO ST_DEPARTMENT(ID, NAME, CODE) VALUES (3, 'Goods inspection', 'GOODS_INSPECTION');
INSERT INTO ST_DEPARTMENT(ID, NAME, CODE) VALUES (4, 'Journey supervision', 'JOURNEY_SUPERVISION');
INSERT INTO ST_DEPARTMENT(ID, NAME, CODE) VALUES (5, 'Human resources', 'HR');
