INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (1, 'Oil', 'OIL');
INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (2, 'Food', 'FOOD');
INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (3, 'Machine tool', 'MACHINE_TOOL');
INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (4, 'Weapon', 'WEAPON');
INSERT INTO ST_GOODS(ID, NAME, CODE) VALUES (5, 'Medicine', 'MEDICINE');