INSERT INTO ST_DESTINATION(ID, NAME, CODE3, LABEL_ID) VALUES (1, 'Moon', 'MOO', 'destination.moon');
INSERT INTO ST_DESTINATION(ID, NAME, CODE3, LABEL_ID) VALUES (2, 'Mars', 'MAR', 'destination.mars');
INSERT INTO ST_DESTINATION(ID, NAME, CODE3, LABEL_ID) VALUES (3, 'Titan', 'TIT', 'destination.titan');