INSERT INTO ST_DESTINATION(ID, NAME, CODE) VALUES (1, 'Moon', 'MOON');
INSERT INTO ST_DESTINATION(ID, NAME, CODE) VALUES (2, 'Mars', 'MARS');
INSERT INTO ST_DESTINATION(ID, NAME, CODE) VALUES (3, 'Titan', 'TITAN');