INSERT INTO ST_DESTINATION(ID, NAME, CODE3, LABEL_ID) VALUES (1, 'Moon', 'MOO', 'destinationId.moon');
INSERT INTO ST_DESTINATION(ID, NAME, CODE3, LABEL_ID) VALUES (2, 'Mars', 'MAR', 'destinationId.mars');
INSERT INTO ST_DESTINATION(ID, NAME, CODE3, LABEL_ID) VALUES (3, 'Titan', 'TIT', 'destinationId.titan');