INSERT INTO ST_DEPARTMENT(ID, NAME, CODE) VALUES (1, 'Law compliance', 'LAW_COMPLIANCE');
INSERT INTO ST_DEPARTMENT(ID, NAME, CODE) VALUES (2, 'Shuttle compliance', 'SHUTTLE_COMPLIANCE');
INSERT INTO ST_DEPARTMENT(ID, NAME, CODE) VALUES (3, 'Good inspection', 'GOOD_INSPECTION');
INSERT INTO ST_DEPARTMENT(ID, NAME, CODE) VALUES (4, 'Journey supervision', 'JOURNEY_SUPERVISION');