-- Généré par Oracle SQL Developer Data Modeler 4.1.1.888
--   à :        2015-09-15 21:23:03 CEST
--   site :      Oracle Database 11g
--   type :      Oracle Database 11g




CREATE TABLE ST_AGREEMENT_RULE
  (
    ID             NUMBER NOT NULL ,
    VERSION        NUMBER NOT NULL ,
    DELETED        CHAR (1) NOT NULL ,
    ID_DESTINATION NUMBER NOT NULL ,
    ID_GOODS       NUMBER NOT NULL ,
    CREATION_DATE  TIMESTAMP NOT NULL ,
    CREATION_USER  VARCHAR2 (50) NOT NULL ,
    UPDATE_DATE    NUMBER NOT NULL ,
    UPDATE_USER    VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE ST_AGREEMENT_RULE ADD CONSTRAINT ST_AGREEMENT_RULE_PK PRIMARY KEY ( ID ) ;


CREATE TABLE ST_AGREEMENT_RULE_AUD
  (
    ID_RULE        NUMBER NOT NULL ,
    VERSION        NUMBER NOT NULL ,
    DELETED        CHAR (1) NOT NULL ,
    ID_DESTINATION NUMBER NOT NULL ,
    ID_GOODS       NUMBER NOT NULL ,
    VERSION_DATE   TIMESTAMP NOT NULL ,
    VERSION_USER   VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE ST_AGREEMENT_RULE_AUD ADD CONSTRAINT ST_AGREEMENT_RULE_AUD_PK PRIMARY KEY ( ID_RULE, VERSION ) ;


CREATE TABLE ST_AGR_RULE_VISA
  (
    ID            NUMBER NOT NULL ,
    ID_RULE       NUMBER NOT NULL ,
    RANK          NUMBER NOT NULL ,
    ID_DEPARTMENT NUMBER NOT NULL ,
    SENIORITY     NUMBER NOT NULL
  ) ;
ALTER TABLE ST_AGR_RULE_VISA ADD CONSTRAINT ST_AGR_RULE_VISA_PK PRIMARY KEY ( ID ) ;


CREATE TABLE ST_AGR_RULE_VISA_AUD
  (
    ID_RULE       NUMBER NOT NULL ,
    RULE_VERSION  NUMBER NOT NULL ,
    RANK          NUMBER NOT NULL ,
    ID_DEPARTMENT NUMBER NOT NULL ,
    SENIORITY     NUMBER NOT NULL
  ) ;
ALTER TABLE ST_AGR_RULE_VISA_AUD ADD CONSTRAINT ST_AGR_RULE_VISA_AUD_PK PRIMARY KEY ( ID_RULE, RULE_VERSION, RANK ) ;


CREATE TABLE ST_CUSTOMER
  (
    ID        NUMBER NOT NULL ,
    "UID"     VARCHAR2 (50) NOT NULL ,
    FULL_NAME VARCHAR2 (200) NOT NULL
  ) ;
ALTER TABLE ST_CUSTOMER ADD CONSTRAINT ST_CUSTOMER_PK PRIMARY KEY ( ID ) ;
ALTER TABLE ST_CUSTOMER ADD CONSTRAINT ST_CUSTOMER_UN_UID UNIQUE ( "UID" ) ;
ALTER TABLE ST_CUSTOMER ADD CONSTRAINT ST_CUSTOMER_UN_NAME UNIQUE ( FULL_NAME ) ;


CREATE TABLE ST_DEPARTMENT
  (
    ID       NUMBER NOT NULL ,
    NAME     VARCHAR2 (200) NOT NULL ,
    LABEL_ID VARCHAR2 (200) NOT NULL
  ) ;
ALTER TABLE ST_DEPARTMENT ADD CONSTRAINT ST_DEPARTMENT_PK PRIMARY KEY ( ID ) ;
ALTER TABLE ST_DEPARTMENT ADD CONSTRAINT ST_DEPARTMENT_UN_NAME UNIQUE ( NAME ) ;
ALTER TABLE ST_DEPARTMENT ADD CONSTRAINT ST_DEPARTMENT_UN_LABELID UNIQUE ( LABEL_ID ) ;


CREATE TABLE ST_DESTINATION
  (
    ID       NUMBER NOT NULL ,
    NAME     VARCHAR2 (200) NOT NULL ,
    CODE3    VARCHAR2 (3) NOT NULL ,
    LABEL_ID VARCHAR2 (200) NOT NULL
  ) ;
ALTER TABLE ST_DESTINATION ADD CONSTRAINT ST_DESTINATION_PK PRIMARY KEY ( ID ) ;
ALTER TABLE ST_DESTINATION ADD CONSTRAINT ST_DESTINATION_UN_NAME UNIQUE ( NAME ) ;
ALTER TABLE ST_DESTINATION ADD CONSTRAINT ST_DESTINATION_UN_CODE UNIQUE ( CODE3 ) ;
ALTER TABLE ST_DESTINATION ADD CONSTRAINT ST_DESTINATION_UN_LABELID UNIQUE ( LABEL_ID ) ;


CREATE TABLE ST_EMPLOYEE
  (
    ID            NUMBER NOT NULL ,
    VERSION       NUMBER NOT NULL ,
    "UID"         VARCHAR2 (50) NOT NULL ,
    FULL_NAME     VARCHAR2 (200) NOT NULL ,
    ID_DEPARTMENT NUMBER NOT NULL ,
    SENIORITY     NUMBER NOT NULL ,
    CREATION_DATE TIMESTAMP NOT NULL ,
    CREATION_USER VARCHAR2 (50) NOT NULL ,
    UPDATE_DATE   TIMESTAMP NOT NULL ,
    UPDATE_USER   VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE ST_EMPLOYEE ADD CONSTRAINT ST_EMPLOYEE_PK PRIMARY KEY ( ID ) ;
ALTER TABLE ST_EMPLOYEE ADD CONSTRAINT ST_EMPLOYEE_UN_UID UNIQUE ( "UID" ) ;
ALTER TABLE ST_EMPLOYEE ADD CONSTRAINT ST_EMPLOYEE_UN_NAME UNIQUE ( FULL_NAME ) ;


CREATE TABLE ST_EMPLOYEE_AUD
  (
    ID_EMPLOYEE   NUMBER NOT NULL ,
    VERSION       NUMBER NOT NULL ,
    "UID"         VARCHAR2 (50) NOT NULL ,
    FULL_NAME     VARCHAR2 (200) NOT NULL ,
    ID_DEPARTMENT NUMBER NOT NULL ,
    SENIORITY     NUMBER NOT NULL ,
    VERSION_DATE  TIMESTAMP NOT NULL ,
    VERSION_USER  VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE ST_EMPLOYEE_AUD ADD CONSTRAINT ST_EMPLOYEE_AUD_PK PRIMARY KEY ( ID_EMPLOYEE, VERSION ) ;


CREATE TABLE ST_GOODS
  (
    ID       NUMBER NOT NULL ,
    NAME     VARCHAR2 (200) NOT NULL ,
    CODE3    VARCHAR2 (3) NOT NULL ,
    LABEL_ID VARCHAR2 (200) NOT NULL
  ) ;
ALTER TABLE ST_GOODS ADD CONSTRAINT ST_GOOD_PK PRIMARY KEY ( ID ) ;
ALTER TABLE ST_GOODS ADD CONSTRAINT ST_GOOD_UN_NAME UNIQUE ( NAME ) ;
ALTER TABLE ST_GOODS ADD CONSTRAINT ST_GOOD_UN_CODE3 UNIQUE ( CODE3 ) ;
ALTER TABLE ST_GOODS ADD CONSTRAINT ST_GOOD_UN_LABELID UNIQUE ( LABEL_ID ) ;


CREATE TABLE ST_REQUEST
  (
    ID                       NUMBER NOT NULL ,
    VERSION                  NUMBER NOT NULL ,
    "UID"                    VARCHAR2 (50) NOT NULL ,
    ID_CUSTOMER              NUMBER NOT NULL ,
    ID_GOODS                 NUMBER NOT NULL ,
    ID_DESTINATION           NUMBER NOT NULL ,
    OVERALL_STATUS           VARCHAR2 (50) NOT NULL ,
    ID_RULE                  NUMBER NOT NULL ,
    RULE_VERSION             NUMBER NOT NULL ,
    AGREEMENT_STATUS         VARCHAR2 (50) NOT NULL ,
    CANCELLATION_COMMENT     VARCHAR2 (1024) ,
    NEXT_AGREEMENT_VISA_RANK NUMBER NOT NULL ,
    CREATION_DATE            TIMESTAMP NOT NULL ,
    CREATION_USER            VARCHAR2 (50) NOT NULL ,
    UPDATE_DATE              TIMESTAMP NOT NULL ,
    UPDATE_USER              VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE ST_REQUEST ADD CONSTRAINT ST_REQUEST_PK PRIMARY KEY ( ID ) ;


CREATE TABLE ST_REQUEST_AGR_VISA
  (
    ID            NUMBER NOT NULL ,
    ID_REQUEST    NUMBER NOT NULL ,
    ID_EMPLOYEE   NUMBER NOT NULL ,
    STATUS        VARCHAR2 (50) NOT NULL ,
    VISA_RANK     NUMBER NOT NULL ,
    ID_DEPARTMENT NUMBER NOT NULL ,
    SENIORITY     NUMBER NOT NULL ,
    VISA_COMMENT  VARCHAR2 (1024) NOT NULL ,
    CREATION_DATE TIMESTAMP NOT NULL
  ) ;
ALTER TABLE ST_REQUEST_AGR_VISA ADD CONSTRAINT ST_REQUEST_AGR_VISA_PK PRIMARY KEY ( ID ) ;


CREATE TABLE ST_REQUEST_NOT_ALLOWED
  (
    ID             NUMBER NOT NULL ,
    ID_DESTINATION NUMBER NOT NULL ,
    ID_GOODS       NUMBER NOT NULL
  ) ;
ALTER TABLE ST_REQUEST_NOT_ALLOWED ADD CONSTRAINT ST_REQUEST_NOT_ALLOWED_PK PRIMARY KEY ( ID ) ;


ALTER TABLE ST_AGREEMENT_RULE ADD CONSTRAINT ST_AGR_RULE_FK_DESTINATION FOREIGN KEY ( ID_DESTINATION ) REFERENCES ST_DESTINATION ( ID ) ;

ALTER TABLE ST_AGREEMENT_RULE ADD CONSTRAINT ST_AGR_RULE_FK_GOODS FOREIGN KEY ( ID_GOODS ) REFERENCES ST_GOODS ( ID ) ;

ALTER TABLE ST_AGR_RULE_VISA_AUD ADD CONSTRAINT ST_AGR_RULE_VISA_AUD_FK_RULE FOREIGN KEY ( ID_RULE, RULE_VERSION ) REFERENCES ST_AGREEMENT_RULE_AUD ( ID_RULE, VERSION ) ;

ALTER TABLE ST_AGR_RULE_VISA ADD CONSTRAINT ST_AGR_RULE_VISA_FK_DPT FOREIGN KEY ( ID_DEPARTMENT ) REFERENCES ST_DEPARTMENT ( ID ) ;

ALTER TABLE ST_AGR_RULE_VISA ADD CONSTRAINT ST_AGR_RULE_VISA_FK_RULE FOREIGN KEY ( ID_RULE ) REFERENCES ST_AGREEMENT_RULE ( ID ) ;

ALTER TABLE ST_EMPLOYEE ADD CONSTRAINT ST_EMPLOYEE_FK_DPT FOREIGN KEY ( ID_DEPARTMENT ) REFERENCES ST_DEPARTMENT ( ID ) ;

ALTER TABLE ST_REQUEST ADD CONSTRAINT ST_REQUEST_AGR_RULE_AUD_FK FOREIGN KEY ( ID_RULE, RULE_VERSION ) REFERENCES ST_AGREEMENT_RULE_AUD ( ID_RULE, VERSION ) ;

ALTER TABLE ST_REQUEST_AGR_VISA ADD CONSTRAINT ST_REQUEST_AGR_VISA_FK_DPT FOREIGN KEY ( ID_DEPARTMENT ) REFERENCES ST_DEPARTMENT ( ID ) ;

ALTER TABLE ST_REQUEST_AGR_VISA ADD CONSTRAINT ST_REQUEST_AGR_VISA_FK_EMPL FOREIGN KEY ( ID_EMPLOYEE ) REFERENCES ST_EMPLOYEE ( ID ) ;

ALTER TABLE ST_REQUEST_AGR_VISA ADD CONSTRAINT ST_REQUEST_AGR_VISA_FK_REQUEST FOREIGN KEY ( ID_REQUEST ) REFERENCES ST_REQUEST ( ID ) ;

ALTER TABLE ST_REQUEST ADD CONSTRAINT ST_REQUEST_FK_CUSTOMER FOREIGN KEY ( ID_CUSTOMER ) REFERENCES ST_CUSTOMER ( ID ) ;

ALTER TABLE ST_REQUEST ADD CONSTRAINT ST_REQUEST_FK_DESTINATION FOREIGN KEY ( ID_DESTINATION ) REFERENCES ST_DESTINATION ( ID ) ;

ALTER TABLE ST_REQUEST ADD CONSTRAINT ST_REQUEST_FK_GOODS FOREIGN KEY ( ID_GOODS ) REFERENCES ST_GOODS ( ID ) ;

ALTER TABLE ST_REQUEST_NOT_ALLOWED ADD CONSTRAINT ST_REQ_NOT_ALL_FK_DEST FOREIGN KEY ( ID_DESTINATION ) REFERENCES ST_DESTINATION ( ID ) ;

ALTER TABLE ST_REQUEST_NOT_ALLOWED ADD CONSTRAINT ST_REQ_NOT_ALL_FK_GOODS FOREIGN KEY ( ID_GOODS ) REFERENCES ST_GOODS ( ID ) ;


-- Rapport récapitulatif d'Oracle SQL Developer Data Modeler :
--
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             40
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0
