drop table ST_DESTINATION if exists;
drop table ST_GOOD exists;
drop table ST_DEPARTMENT if exists;
drop table ST_EMPLOYEE if exists;
drop table ST_EMPLOYEE_AUD  if exists;
drop table ST_AGREEMENT_RULE if exists;
drop table ST_AGR_RULE_VISA if exists;
drop table ST_CUSTOMER if exists;
drop table ST_REQUEST if exists;
drop table ST_AGR_APPLIED_VISA if exists;
drop table ST_AGREEMENT_RULE_AUD if exists;
drop table ST_AGR_RULE_VISA_AUD if exists;