DELETE FROM ST_AGR_RULE_VISA;
DELETE FROM ST_AGREEMENT_RULE;
DELETE FROM ST_AGR_RULE_VISA_AUD;
DELETE FROM ST_AGREEMENT_RULE_AUD;

-- Goods
/*
1,OIL,Oil
2,FOOD,Food
3,MACHINE_TOOL,"Machine tool"
4,MEDICINE,Medicine
5,WEAPON,Weapon
*/

-- Departments
/*
1,LAW_COMPLIANCE,"Law compliance"
2,SHUTTLE_COMPLIANCE,"Shuttle compliance"
3,GOOD_INSPECTION,"Good inspection"
4,JOURNEY_SUPERVISION,"Journey supervision"
5,HR,"Human resources"
 */

-- Rule Earth - Food

INSERT INTO ST_AGREEMENT_RULE(ID, VERSION, ID_DESTINATION, ID_GOODS, CREATION_DATE, CREATION_USER, UPDATE_DATE, UPDATE_USER)
VALUES(1, 1, 1, 2, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');

INSERT INTO ST_AGR_RULE_VISA(ID, ID_RULE, RANK, ID_DEPARTMENT, SENIORITY)
VALUES(1, 1, 0, 1, 20);
INSERT INTO ST_AGR_RULE_VISA(ID, ID_RULE, RANK, ID_DEPARTMENT, SENIORITY)
VALUES(2, 1, 1, 2, 40);
INSERT INTO ST_AGR_RULE_VISA(ID, ID_RULE, RANK, ID_DEPARTMENT, SENIORITY)
VALUES(3, 1, 2, 3, 20);
INSERT INTO ST_AGR_RULE_VISA(ID, ID_RULE, RANK, ID_DEPARTMENT, SENIORITY)
VALUES(4, 1, 3, 4, 30);

-- Rule Moon - Oil

INSERT INTO ST_AGREEMENT_RULE(ID, VERSION, ID_DESTINATION, ID_GOODS, CREATION_DATE, CREATION_USER, UPDATE_DATE, UPDATE_USER)
VALUES(2, 1, 2, 1, CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, 'admin');

INSERT INTO ST_AGR_RULE_VISA(ID, ID_RULE, RANK, ID_DEPARTMENT, SENIORITY)
VALUES(5, 2, 0, 1, 40);
INSERT INTO ST_AGR_RULE_VISA(ID, ID_RULE, RANK, ID_DEPARTMENT, SENIORITY)
VALUES(6, 2, 1, 2, 60);
INSERT INTO ST_AGR_RULE_VISA(ID, ID_RULE, RANK, ID_DEPARTMENT, SENIORITY)
VALUES(7, 2, 2, 3, 40);
INSERT INTO ST_AGR_RULE_VISA(ID, ID_RULE, RANK, ID_DEPARTMENT, SENIORITY)
VALUES(8, 2, 3, 4, 50);